### ISSUE TITLE
Error en construccion complemento Timbre fiscal

### ISSUE THREAD

**Issue by arcanoix** [Kinedu/cfdi-xml#2]
Buenos dias estimado, 

tengo un problema con el uso de la generacion de complementos para timbre fiscal, me esta generando incompleto el nodo. Muestro captura de la forma.

![Screen Shot 2021-06-02 at 09 53 38](https://user-images.githubusercontent.com/6331999/120503036-905e4d80-c388-11eb-8dd2-4ebeff8a32aa.png)

la Idea es que quede como el ejemplo que ustedes muestran: que el nodo de timbre fiscal quede entre complementos. Alguna solucion?? Gracias

**Comment by orlandocharles** [comment]
Hola @thavoo me podrías compartir el código donde generas el timbre fiscal?

**Comment by arcanoix** [comment]
Hola @orlandocharles gracias por tu respuesta pero ya lo resolví, tenia mal armado mi estructura. Muchas gracias.
